### ISSUE TITLE
System.IndexOutOfRangeException: Index was outside the bounds of the array. (in v3.0.290)

### ISSUE THREAD

**Issue by jgammey** [mburbea/koar-item-editor#108]
**Describe the bug**
Loading the attached save causes the error.

**To Reproduce**
 Open the attached saved

**System Information**
 - OS:  Windows 10 build 19042
 - Steam current version
 - Version of the editor: v3.0.290

**Additional context**
[svd_fmt_0_0.zip](https://github.com/mburbea/koar-item-editor/files/6292828/svd_fmt_0_0.zip)

**Comment by mburbea** [comment]
Only user saves are supported, those that start with svd_fmt_5_x. 

the validation broke with the introduction of switch support and will be fixed in the next patch.
