### ISSUE TITLE
System.IndexOutOfRangeException: Index was outside the bounds of the array. (in v3.0.290)

### ISSUE THREAD

**Issue by bkapas3** [mburbea/koar-item-editor#114]
**Describe the bug**
When attempting to load the file to edit i get the system.indexoutofrange exception error
**To Reproduce**
1. Go to  program and hit load file
2. Click on file you want to load
3. hit accept 
4. and error pops right up

**System Information**
 - OS: windows 10
 - Game version [steam
 - Version of the editor: [e.g. 3.0.290]

save editor worked yesterday and today just giving me this error over and over

**Comment by mburbea** [comment]
This is related to fatesworn's release.

**Comment by bkapas3** [comment]
any chance there’s going to be an update to fix anytime soon?
