### ISSUE TITLE
System.IndexOutOfRangeException: Index was outside the bounds of the array. (in v3.0.272)

### ISSUE THREAD

**Issue by iansebryk** [mburbea/koar-item-editor#116]
**Describe the bug**
tried opening a save file `svd_fmt_5_0.sav` in the KoAR Editor an it game me this error.

**To Reproduce**
1. open this file in your KoAR editor:  https://www16.zippyshare.com/v/WqEBE3NS/file.html

**System Information**
 - OS: Win10 Dec2021
 - Game version KoAR RR Fatesworn
 - Version of the editor: 3.0.272

**Additional context**
i think this might be glitched because of the new DLC Fatesworn??  still thought it might be useful to post it in case you're still working on this.

**Comment by mburbea** [comment]
Dupe of #114
