### ISSUE TITLE
System.IndexOutOfRangeException: Index was outside the bounds of the array. (in v3.0.272)

### ISSUE THREAD

**Issue by rintongci** [mburbea/koar-item-editor#123]
Go to load the save file 5 as instructed and the error pops up
![error message](https://user-images.githubusercontent.com/96387151/146683587-b6d4226c-23a7-4b8a-a5a0-a4e02081f1bd.png)

**Comment by mburbea** [comment]
3.0.272 is very old. Please try with the latest version

**Comment by rintongci** [comment]
Just to let you know I thought it was the latest version I was using. I
downloaded it on Nexus primarily

**Comment by mburbea** [comment]
Yes, I updated the one for the remaster. That link is for the original game. The remaster nexus link is here: 
https://www.nexusmods.com/kingdomsofamalurrereckoning/mods/8
I don't test any more with the original game, so I don't know if my changes work in the OG game anymore.
