### ISSUE TITLE
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (in v3.0.462)

### ISSUE THREAD

**Issue by TheAgaRar** [mburbea/koar-item-editor#138]
**Describe the bug**

**To Reproduce**

**System Information**
 - OS: [e.g. Windows 10 2004]
 - Game version [e.g. Stream, GOG and please include the CS]
 - Version of the editor: [e.g. 3.0.347]

**Additional context**
Please also attach a save file that exhibits the issue.
[svdata.zip](https://github.com/mburbea/koar-item-editor/files/7788400/svdata.zip)

**Comment by mburbea** [comment]
Thanks for the file, it appears that the body length detection code was reading the wrong value in your save file. I've improved the detection in #139.

It appears that the header's body length is right after the content packages list.
