### ISSUE TITLE
.NET Errors

### ISSUE THREAD

**Issue by Tanis41493** [mburbea/koar-item-editor#149]
**Describe the bug**
I've downloaded and installed all forms of .NET and it still keeps telling me I need it installed in order to launch it. 

**To Reproduce**
1. Download from here
2. Try to launch it
3. Be given pop-up stating .NET is needed and go to download/install it
4. Post-download/installation, it still says I need it

**System Information**
Attached Dxdiag below

**Additional context**
I downloaded it first from Nexus Mods, but felt that one may have been out of date so I redownloaded it from the repository here and it's still giving me the same issue
[DxDiag.txt](https://github.com/mburbea/koar-item-editor/files/8976397/DxDiag.txt)

**Comment by mburbea** [comment]
You need .net version 5 x64 desktop for windows. 
An eventual update will change the runtime to .net 6 desktop

**Comment by Tanis41493** [comment]
Apologies for the late response, I was temporarily hospitalized for a matter that has thankfully resolved positively. I'll try that when I get out of work today and report here on my success or lack thereof; thank you for the response!

**Comment by bababbel** [comment]
I have the same issue. Tried to install .NET 5 x64 and x86 neither resolves the issue. Also the version that gets installed is 5.0.17 not 5.0 but there is no other download of .NET 5. Don't know if that may be the problem.

**Comment by mburbea** [comment]
And you're positive you installed the windows x64 desktop runtimes?
I will eventually do a release for .net 6, but it's a low priority

**Comment by bababbel** [comment]
Well, I tried installing both the x64 and the x86 version, but the x64 first.

**Comment by mburbea** [comment]
I updated the release to .net 6 x64 desktop::
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.6-windows-x64-installer

**Comment by bababbel** [comment]
Thank you very much. It works now.
