### ISSUE TITLE
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (in v3.0.476)

### ISSUE THREAD

**Issue by KingSpidey91** [mburbea/koar-item-editor#151]
**Describe the bug**
I'm having issues opening my PS4 save data in the editor. Every time I attempt to open the file, I receive an error.

**To Reproduce**
1. Go to 'Save editor
2. Click on open file
3. Scroll down to a save for the PS4

**System Information**
 - OS: [e.g. Windows 10 2004]
 - Game version [e.g. Stream, GOG and please include the CS]
 - Version of the editor: [e.g. 3.0.476]

**Additional context**
Please also attach a save file that exhibits the issue.

**Comment by KingSpidey91** [comment]
![Capture](https://user-images.githubusercontent.com/111145073/184413743-cf53f97b-0b26-467a-94cb-911b64bbaabe.PNG)

**Comment by mburbea** [comment]
Can you fill out the form, and or attach the save file?

**Comment by KingSpidey91** [comment]
I was able to figure it out. I had to export the file through the advance mode on Save Wizard.
