### ISSUE TITLE
Corrupts Saves in Remaster! :(

### ISSUE THREAD

**Issue by Jayshua83** [mburbea/koar-item-editor#58]
This corrupts my remaster saves! :(

I want my extra quest items GONE! lol :(

**Comment by mburbea** [comment]
I'm working on fixing this in #55 . 
If you're building from source you can try that branch, but it's incomplete at the moment. 

There are a few differences between saves in the original and the remaster:
- The remaster treats the autosave, the tutorial, and the quicksave as special files and keeps them in memory once the starts. So realistically, the editor can now only mess with files of the format svd_fmt_5_x.sav
- The remaster uses a new container that allocates a 6kb header and 4mb body for save data. Once that 4mb is exceeded it switches to zlib compression. I don't know what this looks like yet.
- The remaster uses a CRC32 check on both the header and the save file.  
- The format for stashed items is different.
- The data files I use are for the original, not the remaster. There is no current way to regenerate these files for the remaster.
