### ISSUE TITLE
Clicking open file on v3.0.2.18 and v3.0.2.20 crash the editor

### ISSUE THREAD

**Issue by Aioxas** [mburbea/koar-item-editor#67]
Tested on the above versions and on v3.0.2.12, as that was the latest version that I can actually click Open File and it will open the dialog. After closing and reopening to maybe try something else, the above versions keep crashing, v3.0.2.12 doesn't.

Guessing by what I saw on v3.0.2.12, it seems that after clicking close on the update window, it's not opening the open file dialog.

**Comment by mburbea** [comment]
As silly as this sounds, have you tried restarting your PC and trying again?

I've had this happen while debugging for some reason and a restart helps.

**Comment by Aioxas** [comment]
Had deleted it. Fresh download still caused ctd, and restarting showed same behavior. So the config was saved independent of the folder.

**Comment by mburbea** [comment]
The config is saved to %localappdata%\-\ (some folder here).
Try deleting that and see if it fixes the issue.

**Comment by Aioxas** [comment]
deleted it, but still same issue, hardfixed it by moving the string from 0.212 to 0.220's user.config ```
            <setting name="LastDirectory" serializeAs="String">
                <value>C:\Program Files (x86)\Steam\userdata\meow\1041720\remote\autocloud\save</value>
            </setting>```
