### ISSUE TITLE
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.Parameter name: length (in v3.0.267)

### ISSUE THREAD

**Issue by webravager** [mburbea/koar-item-editor#80]
**Describe the bug**

**To Reproduce**

**System Information**
 - OS: [e.g. Windows 10 2004]
 - Game version [e.g. Stream, GOG and please include the CS]
 - Version of the editor: [e.g. 3.0.347]

**Additional context**
Please also attach a save file that exhibits the issue.

**Comment by mburbea** [comment]
Can you please fill out the bug report form and attach a save file?

**Comment by ellej** [comment]
I ran into this issue too. It's easy to reproduce.

Create a new character.
Get the first weapon.
Add two item buffs to the weapon in the save editor.

It will crash the editor (or the game) when you try to load the save file.
I get this on the steam version of the game with version v3.0.267 of the editor.

[svd_fmt_5_2.zip](https://github.com/mburbea/koar-item-editor/files/5308327/svd_fmt_5_2.zip)

**Comment by mburbea** [comment]
Thanks for the save and the explanation of how to repro!
I'll fix it asap. Dang precedence rules.
