### ISSUE TITLE
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.Parameter name: start (in v3.0.270)

### ISSUE THREAD

**Issue by PiotrKowalczyk13** [mburbea/koar-item-editor#82]
Bug shows when loading save attached to editor.

To reproduce:
Just open save file with editor.

**System Information**
 - OS: Windows 10 1803
 - Game version: Steam
 - Version of the editor: 3.0.270

[svd_fmt_5_22.zip](https://github.com/mburbea/koar-item-editor/files/5314710/svd_fmt_5_22.zip)

**Comment by mburbea** [comment]
Was this save previously edited? It looks like the active buff count was not set correctly in this file for your "Ravenclaw" item.
