### ISSUE TITLE
System.Runtime.InteropServices.COMException: OpenClipboard failed (Exception from HRESULT: 0x800401D0 (CLIPBRD_E_CANT_OPEN)) (in v3.0.272)

### ISSUE THREAD

**Issue by programmerzlp** [mburbea/koar-item-editor#85]
**Describe the bug**

**To Reproduce**

**System Information**
 - OS: [e.g. Windows 10 2004]
 - Game version [e.g. Stream, GOG and please include the CS]
 - Version of the editor: [e.g. 3.0.347]

**Additional context**
Please also attach a save file that exhibits the issue.

**Comment by mburbea** [comment]
Can you fill in the bug report form?
